#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Jonny Reckless
"""Embed the shipped NNUE network into the engine binary.

Reads a .nnue file and writes a C translation unit defining `embedded_network_data` /
`embedded_network_size` (declared in src/nnue.h). The Makefile runs this when the net changes and
compiles the output once into build/embedded_net.o, which every binary links — the engine falls back
to this embedded copy whenever no EvalFile is set or the requested file fails to load, so a bare
binary is always full strength with no external files.

Usage: python3 tools/embed_net.py <net.nnue> <out.c>
"""
import sys


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: embed_net.py <net.nnue> <out.c>")
    net_path, out_path = sys.argv[1], sys.argv[2]
    data = open(net_path, "rb").read()
    if not (data.startswith(b"ZNNUE") and len(data) > 8):
        raise SystemExit(f"{net_path} does not look like a Zenith .nnue file")
    with open(out_path, "w") as out:
        out.write("// Generated by tools/embed_net.py — the embedded NNUE network. Do not edit.\n")
        out.write(f"// Source: {net_path} ({len(data):,} bytes)\n")
        out.write("#include <stddef.h>\n\n")
        out.write("const unsigned char embedded_network_data[] = {\n")
        for offset in range(0, len(data), 20):
            chunk = data[offset : offset + 20]
            out.write("    " + ",".join(str(byte) for byte in chunk) + ",\n")
        out.write("};\n\n")
        out.write("const size_t embedded_network_size = sizeof embedded_network_data;\n")
    print(f"embedded {net_path} ({len(data):,} bytes) -> {out_path}")


if __name__ == "__main__":
    main()
