#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Jonny Reckless
"""Embed the shipped opening book into the engine binary.

Reads a Polyglot .bin and writes a C translation unit defining `embedded_book_data` /
`embedded_book_size` (declared in src/book.h). The Makefile compiles the output once into
build/embedded_book.o, which every binary links — `setoption name OwnBook value true` then works with
no BookFile at all (OwnBook still defaults to false; testing stays bookless).

Usage: python3 tools/embed_book.py <book.bin> <out.c>
"""
import sys


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: embed_book.py <book.bin> <out.c>")
    book_path, out_path = sys.argv[1], sys.argv[2]
    data = open(book_path, "rb").read()
    if len(data) == 0 or len(data) % 16 != 0:
        raise SystemExit(f"{book_path} is not a Polyglot book (size not a positive multiple of 16)")
    with open(out_path, "w") as out:
        out.write("// Generated by tools/embed_book.py — the embedded opening book. Do not edit.\n")
        out.write(f"// Source: {book_path} ({len(data):,} bytes, {len(data) // 16:,} entries)\n")
        out.write("#include <stddef.h>\n\n")
        out.write("const unsigned char embedded_book_data[] = {\n")
        for offset in range(0, len(data), 20):
            chunk = data[offset : offset + 20]
            out.write("    " + ",".join(str(byte) for byte in chunk) + ",\n")
        out.write("};\n\n")
        out.write("const size_t embedded_book_size = sizeof embedded_book_data;\n")
    print(f"embedded {book_path} ({len(data):,} bytes) -> {out_path}")


if __name__ == "__main__":
    main()
